import Cookies from "js-cookie";
import Jwt from "jsonwebtoken";
import { days, minutes } from "./aboutTime";

// Generated by https://quicktype.io

export interface UserInterface {
  id: string;
  name: string;
  username: string;
  email: string;
  photo: string;
  google_token: string;
  iat: number;
  exp: number;
}

const userToken = {
  isLogined(): boolean | UserInterface {
    let cookiesStore = Cookies.get();
    if (!cookiesStore?.refreshToken) return false;

    let user_decoded = Jwt.decode(cookiesStore.refreshToken);
    return user_decoded as UserInterface;
  },
  saveToken(refresh_token: string, access_token: string) {
    Cookies.set("refreshToken", refresh_token, {
      path: "/",
      expires: new Date(Date.now() + days(30)),
    });
    Cookies.set("accessToken", access_token, {
      path: "/",
      expires: new Date(Date.now() + minutes(10)),
    });
  },
};

export default userToken;
